version: "3.8"
services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
    name: wikwik-db