version: "3.8"
services:
  postgres-wikwik:
      image: postgres:13.2
      ports:
          - "5432:5432"
      volumes:
          - "postgres-data:/var/lib/postgresql/data"
      environment:
          POSTGRES_DB: wikwik
          POSTGRES_USER: wikwik_api
          POSTGRES_PASSWORD: topsecret

volumes:
    postgres-data: